package xxx.joker.libs.repo.exceptions;

public enum ErrorType {

    DESIGN_ANNOTATION_NOT_ALLOWED,
    DESIGN_FIELD_NOT_UNIQUE,
    DESIGN_WRONG_FIELD_TYPE,
    DESIGN_CIRCULAR_DEPENDENCIES,
    RUNTIME_CLASS_NOT_MANAGED,
    RUNTIME_UNEXPECTED_ERROR,
    RUN_ADD_EXISTING_RESOURCE,


}
